import Providers from "@/components/Providers";
import { Divider } from "@nextui-org/divider";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const font = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" dark">
      <body className={font.className}>
        <Providers>
          <div className=" flex min-h-[100dvh] flex-col">
            <header className=" grid h-16 flex-none place-items-center p-4">
              Header
            </header>
            <Divider />
            <main className=" grid flex-grow place-items-center p-4">
              {children}
            </main>
            <Divider />
            <footer className=" grid h-16 flex-none place-items-center p-4">
              Footer
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
